name: A developers notebook
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
url: "https://stefanjenkner.github.io"
title: A developer's notebook
author: Stefan Jenkner
email: stefan@jenkner.org
pligins:
  - jekyll-auto-image
  - jekyll-email-protect
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache/
twitter_username: stefanjenkner
github_username: stefanjenkner
