name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build
        run: pelican -v
      - name: Publish
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: master